apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: train-classifier-pipeline-
spec:
  entrypoint: pipeline
  arguments:
    parameters:
      - name: config
        value: configs/iris_mlp_classifier.json
  templates:
    - name: preprocess
      container:
        image: preprocess-job:latest
        imagePullPolicy: Never
        command: ["uv", "run", "python", "scripts/preprocess.py"]
        args: ["--config", "{{workflow.parameters.config}}"]
        envFrom:
          - secretRef:
              name: s3-credentials
        env:
          - name: PYTHONUNBUFFERED
            value: "1"
          - name: S3_ENDPOINT_URL
            value: "http://host.docker.internal:7000"
        volumeMounts:
          - name: configs
            mountPath: /app/configs
            readOnly: true
      volumes:
        - name: configs
          configMap:
            name: train-configs

    - name: train
      container:
        image: train-job:latest
        imagePullPolicy: Never
        command: ["uv", "run", "python", "scripts/train.py"]
        args: ["--config", "{{workflow.parameters.config}}"]
        envFrom:
          - secretRef:
              name: s3-credentials
        env:
          - name: PYTHONUNBUFFERED
            value: "1"
          - name: S3_ENDPOINT_URL
            value: "http://host.docker.internal:7000"
          - name: MLFLOW_TRACKING_URI
            value: "http://host.docker.internal:5000"
          - name: MLFLOW_S3_ENDPOINT_URL
            value: "http://host.docker.internal:7000"
        volumeMounts:
          - name: configs
            mountPath: /app/configs
            readOnly: true
      volumes:
        - name: configs
          configMap:
            name: train-configs

    - name: pipeline
      dag:
        tasks:
          - name: preprocess
            template: preprocess
          - name: train
            template: train
            dependencies: [preprocess]
